server:
  port: 8081
spring:
  application:
    name: 2022boot
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
      username: dy
      password: 123456
mybatis-plus:
  configuration:
   # map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   # mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
    #雪花算法
      id-type: auto